# Generated by Django 5.2.8 on 2025-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
